### ISSUE TITLE
Add Single Pass Instanced Rendering support

### ISSUE THREAD

**Issue by johannesugb** [johannesugb/VolumetricLinesUnity#5]
Support for Single Pass Instanced Rendering has been requested.
Further information: https://docs.unity3d.com/Manual/SinglePassInstancing.html

**Comment by ilmatematico** [comment]
agree, with VR only left eye is rendering the eye in SPI

**Comment by jonathanmorlen** [comment]
Only my left eye is rendering as well.

**Comment by johannesugb** [comment]
Can you confirm that the problem persists with the latest version? I.e. which includes the changes of commit https://github.com/johannesugb/VolumetricLinesUnity/commit/f6569bcc0847c2cdc2cbba4605c461629bcce7ca

**Comment by jonathanmorlen** [comment]
Yes, just checked the _LineStripShader.cginc and it has all the changes from that commit. I am using an HP Reverb. and Unity 2020.2.6f1

**Comment by jorgeolothar** [comment]
Any progress on this issue?

**Comment by johannesugb** [comment]
Yes, there is a potential fix. I've updated all branches some minutes ago with code that has been reported to fix the single pass instanced rendering issue. I have yet to test myself in VR, but maybe if you could checkout the code and report back if it has solved it for you, that would help a lot.

Just ensure that you checkout the code from the appropriate branches, i.e. those targeting with the most up-to-date Unity editor versions, I suppose, which are:
- [`unity2019`](https://github.com/johannesugb/VolumetricLinesUnity/tree/unity2019), and
- [`universal_render_pipeline`](https://github.com/johannesugb/VolumetricLinesUnity/tree/universal_render_pipeline) (also Unity 2019)

I'll wait a few days for feedback and try to test myself in VR before I'll update the assets in the Asset Store.

**Comment by jorgeolothar** [comment]
Those changes worked.
Tested on Unity 2021.1.19, OpenVR (Steam Valve Index , Single Pass Instanced) and Oculus (Rift, Single Pass Instanced)

**Comment by johannesugb** [comment]
Thank you :)
