### ISSUE TITLE
MeshRenderer-Material TypeMismatch

### ISSUE THREAD

**Issue by Monsoonexe** [johannesugb/VolumetricLinesUnity#6]
Using Unity 2019.2.8f1 Personal.
Imported Volumetric Lines on 4/27/2020.
Upon selecting any of the given Prefabs, Unity continuously attempts to refresh the Inspector.  The cursor turns to a blue circle and is slow to respond.  I notice that in the MeshRenderer.Materials[] section, the only element says "TypeMismatch".  Using circle select to pick correct material has no effect.

**Comment by johannesugb** [comment]
Hello and thanks for reporting this problem.

I am aware of the issue and will submit a fix to the Asset Store in
the next few days. The code on GitHub should already be fixed, if you dont
want to wait for the update.

All the best,
Johannes

**Comment by johannesugb** [comment]
Are you using the latest version from GitHub? I.e. commit f921a4b5079212e1f23dc397adfb46d14d92df87 or newer?

**Comment by Monsoonexe** [comment]
Thanks for the reply! Also, thanks for the sweet asset pack.  I use this in
my game jam games all the time.

I experienced this problem when I downloaded the asset from the Unity Asset
Store. I haven't pulled down anything from github.

**Comment by johannesugb** [comment]
Okay, thanks for your feedback. 
I will submit a new version to the Asset Store soon, which should hopefully solve your problem.

I will post a comment again after the new version has been made available on the asset store and will kindly ask you to test whether the problem has been fixed.

**Comment by Monsoonexe** [comment]
Sure, no problem.

**Comment by johannesugb** [comment]
May I ask you to update the package from the Asset Store and check whether the problem has been solved?

**Comment by Monsoonexe** [comment]
Hello Johannes,

I updated the package from the Unity Asset Store and tested it in Unity
2019.2.8 and Unity 2019.3, and the package works great in both.  Thanks for
taking the time to maintain this asset.

--Richard Osborn

**Comment by johannesugb** [comment]
You are very welcome.
Thanks for testing!

**Comment by Monsoonexe** [comment]
Hello Johannes,

I am upgrading my project from the built-in render pipeline to the new
Unity Universal Render Pipeline. I notice that you have a separate project
on GitHub for use with the URP.
However, I am not understanding exactly how to upgrade. Since I already
have this in my project, do I need to first delete it and then download the
entire project from scratch? Or do I need to just add the "Assets/
VolumetricLines/UniversalRenderPipeline/" folder to my existing project?

Thanks for your time,

--Richard Osborn

**Comment by johannesugb** [comment]
On the Asset Store, the URP-package is an addon-package. I.e. if you install from the Asset Store, you'll have to install

1. The base package [Volumetric Lines](https://assetstore.unity.com/packages/tools/particles-effects/volumetric-lines-29160), and then 
2. the addon-package [Volumetric Lines URP](https://assetstore.unity.com/packages/tools/particles-effects/volumetric-lines-urp-164644).
            
-----
                 
However, if you use the GitHub version, you can just take everything from the [universal_render_pipeline](https://github.com/johannesugb/VolumetricLinesUnity/tree/universal_render_pipeline) branch, which includes the full source code for the Standard/Build-In Render Pipeline AND for the Universal Render Pipeline. Just copy everything from `project/Assets/VolumetricLines/` into your project. 

I would advise to replace all the existing assets as well, to ensure that you are using the latest version. If you are certain that you already have the latest version, then just adding `project/Assets/VolumetricLines/UniversalRenderPipeline` should work just fine.
