### ISSUE TITLE
Unable to save prefab

### ISSUE THREAD

**Issue by Joscho2** [johannesugb/VolumetricLinesUnity#8]
It is unable to save shader properties. Only in some random constelation in some random time it is possible to save volumetric line.
![obrázok](https://user-images.githubusercontent.com/26082615/109075416-5f231100-76f9-11eb-86d1-08edc0a29294.png)

**Comment by johannesugb** [comment]
How can the problem be reproduced?

**Comment by johannesugb** [comment]
Haven't seen this problem reported elsewhere and since there hasn't been any reply since Feb 25, closing this now.
